"""empty message

Revision ID: a76b02ac31d0
Revises: 50e0d666b0e8
Create Date: 2018-10-24 23:13:35.557236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76b02ac31d0'
down_revision = '50e0d666b0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
